import Image from "next/image";
import Link from "next/link";
import { InquiryForm } from "@/components/InquiryForm";

type TextItem = readonly [string, string];

const ChipRow = ({ items }: { items: readonly string[] }) => (
  <div className="bw-chip-row">{items.map((item) => <span key={item}>{item}</span>)}</div>
);

const CardGrid = ({ items, className = "bw-card-grid" }: { items: readonly TextItem[]; className?: string }) => (
  <div className={className}>{items.map(([title, copy]) => <article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div>
);

const SectionIntro = ({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) => (
  <div className="product-section-intro bw-section-intro"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>
);

const ComplianceBlock = ({ className = "" }: { className?: string }) => (
  <section className={`section ${className}`}>
    <div className="container bw-two-column">
      <div><span className="eyebrow">Documentation</span><h2>Compliance &amp; Documentation</h2><p>Huanyu maintains current domestic manufacturing authorization and model-specific CCC documentation for selected building-wire products. Exact model scope is confirmed against the applicable certificate and order specification.</p><Link className="text-link" href="/quality">Review Quality &amp; Credentials →</Link></div>
      <aside className="review-note">CCC is a Chinese domestic conformity requirement and is not presented as destination-market certification. Destination-market certification, inspection or conformity requirements should be specified before quotation.</aside>
    </div>
  </section>
);

const QualityBlock = ({ bvr = false }: { bvr?: boolean }) => (
  <section className="section section-muted">
    <div className="container bw-quality-panel">
      <div><span className="eyebrow">Quality control</span><h2>Building Wire Quality Control at Huanyu</h2><ul className="detail-list">{(bvr ? ["Strand construction verification", "DC conductor resistance checks", "Insulation and dimensional checks", "Spark and routine testing according to the confirmed standard", "Release documentation review"] : ["Incoming conductor and insulation material checks", "Construction and dimensional checks during production", "Spark testing", "Electrical and physical routine tests aligned with the confirmed standard", "Release documentation and packing review"]).map((item) => <li key={item}>{item}</li>)}</ul><Link className="button button-secondary" href="/quality">View Quality &amp; Testing</Link></div>
    </div>
  </section>
);

const productFamilies = [
  { reference: "BV", title: "450/750V PVC Insulated Single-Core Building Wire", copy: "Rigid copper conductor with PVC insulation for fixed building wiring. Solid or stranded rigid conductor construction is selected according to conductor size and the confirmed specification. 60227 IEC 01 is referenced for applicable constructions.", chips: ["450/750V", "Single Core", "Rigid Copper", "PVC"], href: "/products/single-core-pvc-building-wire", cta: "View BV Details", image: "/images/products/building-wires/bw-bv-product.png", imageAlt: "Huanyu BV rigid copper single-core PVC insulated building wire" },
  { reference: "BVR", title: "450/750V Flexible PVC Insulated Building Wire", copy: "Flexible stranded copper conductor with PVC insulation for fixed wiring routes where easier bending and routing are required.", chips: ["450/750V", "Single Core", "Flexible Copper", "PVC"], href: "/products/flexible-pvc-building-wire", cta: "View BVR Details", image: "/images/products/building-wires/bw-bvr-product.png", imageAlt: "Huanyu BVR flexible stranded copper PVC insulated building wire" },
  { reference: "BVVB", title: "300/500V Flat PVC Insulated & Sheathed Building Cable", copy: "Flat two-core copper building cable with PVC insulation and PVC outer sheath for indoor fixed wiring applications.", chips: ["300/500V", "2 Core", "PVC/PVC", "Flat Construction"], href: "#bvvb", cta: "View BVVB Sizes", image: "/images/products/building-wires/bw-bvvb-product.png", imageAlt: "Huanyu BVVB flat two-core PVC insulated and sheathed building cable" },
];

const hubComparison = [
  ["Rated voltage", "450/750V", "450/750V"], ["Conductor material", "Copper", "Copper"], ["Conductor type", "Rigid", "Flexible stranded"], ["Insulation", "PVC", "PVC"], ["Sheath", "None", "None"], ["Typical role", "General fixed wiring", "Fixed wiring requiring easier bending / routing"],
];

export function BuildingWiresHubPage() {
  const supplyOptions: TextItem[] = [["Sizes", "Common building-wire sizes and extended sections are reviewed by product family and confirmed construction."], ["Colours", "Common electrical wire colours and project-specific colour schedules can be reviewed before order confirmation."], ["Coil Length", "Typical coil length is 100 m. Other export coil lengths, marking and packing can be reviewed according to confirmed order requirements."], ["Marking & Packing", "Cable marking, coil labels and export packing details are confirmed with the order specification."], ["OEM / Private Label", "Private-label marking and packing can be reviewed according to quantity and confirmed requirements."]];
  const buyerChecks: TextItem[] = [["Conductor Construction", "Solid, stranded rigid and flexible stranded constructions are not interchangeable descriptions."], ["DC Conductor Resistance", "Electrical resistance is a key performance check alongside nominal cross section."], ["Insulation Control", "Insulation dimensions and integrity must follow the confirmed product specification."], ["Finished Dimensions", "Finished diameter or flat cable dimensions should match the confirmed construction."], ["Actual Coil Length", "Supplied length and packing should match the purchase specification."]];
  const applications: TextItem[] = [["Residential Wiring", "Fixed interior wiring routes in houses and apartments, subject to the applicable local electrical code."], ["Commercial Building Wiring", "General interior fixed wiring for offices, shops and commercial facilities."], ["Conduit & Protected Wiring", "Single-core PVC wires used in suitable conduit or protected wiring systems according to the installation design."], ["Distribution Boards & Internal Wiring", "Flexible BVR wiring for routes where easier bending and routing are required within the confirmed application."]];
  const orderSteps: TextItem[] = [["Send the specification", "Product or designation, size, colour, standard, quantity and destination."], ["Technical review", "Confirm conductor construction, standard, testing and document requirements."], ["Quotation", "Prepare price and commercial terms against the confirmed specification."], ["Packing confirmation", "Confirm coil length, marking and private-label requirements where applicable."]];
  return <>
    <section className="product-detail-hero xlpe-product-hero bw-hero"><div className="container product-detail-grid"><div><Link className="back-link" href="/products">Back to all products</Link><span className="eyebrow light">Building Wires</span><h1>Building Wires &amp; House Wiring Cables</h1><p>Huanyu manufactures PVC insulated building wires for residential, commercial and general fixed wiring. The current range centers on BV rigid single-core building wire, BVR flexible stranded wire and BVVB flat sheathed cable, with construction and documentation reviewed against the buyer&apos;s required specification.</p><div className="xlpe-hero-badges">{["450/750V", "300/500V", "Copper Conductor", "PVC Insulated", "BV · BVR · BVVB"].map((item) => <span key={item}>{item}</span>)}</div><div className="hero-actions"><Link className="button" href="#product-range">Explore Product Range</Link><Link className="button button-ghost" href="#inquiry" data-ga-event="rfq_click" data-ga-cta-location="product_hero" data-ga-product-slug="building-wires-flexible-cables">Request a Quote</Link></div></div><div className="product-detail-image bw-hero-image"><Image src="/images/products/building-wires/bw-hub-hero.png" alt="Huanyu PVC building wires including rigid, flexible stranded and flat sheathed copper wire constructions" width={1792} height={896} sizes="(max-width: 980px) 100vw, 45vw" priority /></div></div></section>

    <section className="section" id="product-range"><div className="container"><SectionIntro eyebrow="Product range" title="Building Wire Product Range" copy="Start with conductor construction and cable form, then confirm the required standard, size, colour and packing before quotation." /><div className="bw-family-grid">{productFamilies.map((product) => <article className="bw-family-card" key={product.reference}><Link className="bw-family-image-link" href={product.href} aria-label={`${product.cta}: ${product.title}`}><Image src={product.image} alt={product.imageAlt} width={768} height={512} sizes="(max-width: 640px) 100vw, (max-width: 980px) 50vw, 33vw" /></Link><span className="eyebrow">{product.reference}</span><h3><Link className="bw-family-title-link" href={product.href}>{product.title}</Link></h3><p>{product.copy}</p><ChipRow items={product.chips} /><Link className="button button-small bw-family-cta" href={product.href}>{product.cta} →</Link></article>)}</div></div></section>

    <section className="section section-muted"><div className="container"><SectionIntro eyebrow="Supply review" title="Supply Options for Importers, Distributors & Project Buyers" /><CardGrid items={supplyOptions} className="bw-card-grid bw-five-grid bw-mobile-supply-grid" /></div></section>

    <section className="section"><div className="container bw-media-grid"><div><span className="eyebrow">Construction guide</span><h2>Choose by Conductor &amp; Cable Construction</h2><div className="bw-choice-grid"><article><strong>Rigid single-core</strong><span>60227 IEC 01 (BV)</span></article><article><strong>Flexible stranded single-core</strong><span>BVR</span></article><article><strong>Flat insulated &amp; sheathed</strong><span>BVVB</span></article></div><p className="review-note">The Chinese model reference helps identify the product family; final conductor construction, dimensions and applicable standard are confirmed before quotation.</p></div><div className="bw-product-image"><Image src="/images/products/building-wires/bw-bv-bvr-conductor-comparison.png" alt="Comparison of BV solid and stranded rigid conductors with BVR flexible stranded conductor" width={768} height={512} sizes="(max-width: 980px) 100vw, 44vw" /></div></div></section>

    <section className="section section-muted"><div className="container"><SectionIntro eyebrow="Size overview" title="Common Building Wire Sizes" /><div className="bw-size-grid"><article><h3>BV</h3><p>Commonly requested</p><ChipRow items={["1.5", "2.5", "4", "6", "10", "16", "25", "35 mm²"]} /><p><strong>Extended current commercial range:</strong> 50–300 mm²</p><p>60227 IEC 01 reference for applicable constructions.</p></article><article><h3>BVR</h3><p>Reference sizes with current technical data</p><ChipRow items={["2.5", "4", "6", "10", "16", "25", "35", "50", "70 mm²"]} /><p>Additional sizes are reviewed against the required conductor construction and product specification before quotation.</p></article><article><h3>BVVB</h3><p>Current listed sizes</p><ChipRow items={["2×1", "2×1.5", "2×2.5", "2×4", "2×6 mm²"]} /></article></div></div></section>

    <section className="section"><div className="container"><SectionIntro eyebrow="BV vs BVR" title="Different Conductor Construction, Different Installation Flexibility" /><p className="bw-swipe-hint">Swipe horizontally to compare →</p><div className="xlpe-table-wrap"><table className="xlpe-table bw-table"><thead><tr><th>Item</th><th>BV</th><th>BVR</th></tr></thead><tbody>{hubComparison.map(([item, bv, bvr]) => <tr key={item}><th scope="row">{item}</th><td>{bv}</td><td>{bvr}</td></tr>)}</tbody></table></div><p className="bw-table-note">A rigid BV conductor may be solid or stranded depending on the size and confirmed construction. BVR uses a multi-strand flexible conductor.</p><div className="bw-example-row"><span>BV 2.5 mm² solid rigid: <strong>1 × 1.78 mm</strong></span><span>BV 2.5 mm² stranded rigid: <strong>7 × 0.68 mm</strong></span><span>BVR 2.5 mm² flexible stranded: <strong>19 × 0.41 mm</strong></span></div></div></section>

    <section className="section section-muted"><div className="container bw-two-column"><div><span className="eyebrow">Specification review</span><h2>Have a Required Standard or Cable Designation?</h2><p>Building-wire standards and product designations vary by market. Send the required standard, designation or technical specification with your RFQ so the conductor class, construction, dimensions, testing, marking and documentation can be reviewed before supply is confirmed.</p></div><aside className="bw-standard-card"><h3>Current Chinese Product References</h3><ul><li>GB/T 5023.3-2008</li><li>JB/T 8734.2-2016</li></ul><p>BV, BVR and BVVB are Chinese product references and are not presented as automatic equivalents of IEC, EN, BS or other national cable designations.</p></aside></div></section>

    <section className="section"><div className="container"><SectionIntro eyebrow="Buyer checklist" title="What Buyers Should Check Beyond Nominal Wire Size" /><div className="bw-number-grid bw-mobile-checklist">{buyerChecks.map(([title, copy], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <QualityBlock />
    <ComplianceBlock />

    <section className="section section-muted" id="bvvb"><div className="container bw-media-grid"><div><span className="eyebrow">BVVB</span><h2>300/500V Flat PVC Insulated &amp; Sheathed Building Cable</h2><p>BVVB uses two PVC-insulated copper cores within a flat PVC outer sheath. The flat construction is intended for indoor fixed wiring applications where the applicable local electrical code and project design permit this cable type.</p><ChipRow items={["2 × 1 mm²", "2 × 1.5 mm²", "2 × 2.5 mm²", "2 × 4 mm²", "2 × 6 mm²"]} /><div className="bw-flow"><span>Copper Conductor</span><span>PVC Insulation</span><span>PVC Outer Sheath</span><span>Flat 2-Core Construction</span></div></div><div className="bw-product-image"><Image src="/images/products/building-wires/bw-bvvb-product.png" alt="Huanyu BVVB 300/500V flat two-core PVC insulated and sheathed building cable" width={768} height={432} sizes="(max-width: 980px) 100vw, 44vw" /></div></div></section>

    <section className="section"><div className="container"><SectionIntro eyebrow="Applications" title="Typical Building Wire Applications" /><CardGrid items={applications} className="bw-card-grid bw-four-grid" /><p className="review-note bw-wide-note">Final conductor size, cable construction and installation method must follow the applicable local electrical code and project specification.</p></div></section>

    <section className="section section-muted"><div className="container bw-two-column"><article><span className="eyebrow">Packing</span><h2>Coil Length, Marking &amp; Export Packing</h2><p>Typical coil length is 100 m. Other export coil lengths, marking and packing can be reviewed according to confirmed order requirements.</p><ChipRow items={["100 m Typical Coil", "Custom Export Length", "Cable Marking", "Coil / Carton Labels", "Private-Label Review"]} /></article><article><span className="eyebrow">Manufacturer</span><h2>Manufactured by Huanyu Cable</h2><p>Building wires are part of Huanyu&apos;s current cable manufacturing range in Hefei, China. Production and release are supported by material checks, in-process control, routine testing and specification review before quotation and shipment.</p><div className="hero-actions"><Link className="button button-secondary" href="/about">About Huanyu</Link><Link className="text-link" href="/quality">Quality &amp; Testing →</Link></div></article></div></section>

    <section className="section"><div className="container"><SectionIntro eyebrow="Order process" title="How to Start a Building Wire Order" /><div className="bw-number-grid bw-four-grid bw-mobile-timeline">{orderSteps.map(([title, copy], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="section quote-section" id="inquiry"><div className="container quote-grid"><div><span className="eyebrow light">Quotation review</span><h2>Request a Building Wire Quotation</h2><p>Send the product family, size, standard, colour, coil length, quantity and destination. Partial information is welcome for initial review.</p><div className="bw-rfq-help"><strong>For distributor / wholesale orders</strong><span>Size · Colour · Coil Length · Quantity · Packing · Private Label</span><strong>For project / contractor orders</strong><span>Standard · Voltage · Conductor Construction · Size · Testing · Documentation · Quantity</span></div></div><InquiryForm compact /></div></section>
  </>;
}

const bvSpecs = [["Product reference", "BV / 60227 IEC 01 where applicable"], ["Rated voltage", "450/750V"], ["Core", "Single core"], ["Conductor", "Copper"], ["Conductor type", "Rigid — solid or stranded depending on confirmed construction"], ["Insulation", "PVC"], ["Outer sheath", "None"], ["Current Huanyu commercial size range", "1.5–300 mm²"], ["Typical packing", "Typical coil length is 100 m. Other export coil lengths, marking and packing can be reviewed according to confirmed order requirements."]];
const bvrSpecs = [["Product reference", "BVR"], ["Rated voltage", "450/750V"], ["Core", "Single core"], ["Conductor", "Copper"], ["Conductor type", "Flexible stranded"], ["Insulation", "PVC"], ["Outer sheath", "None"], ["Reference technical range on this page", "2.5–70 mm²"], ["Typical packing", "Typical coil length is 100 m. Other export coil lengths, marking and packing can be reviewed according to confirmed order requirements."]];
const bvrConstruction = [["2.5 mm²", "19 / 0.41 mm"], ["4 mm²", "19 / 0.52 mm"], ["6 mm²", "19 / 0.64 mm"], ["10 mm²", "49 / 0.52 mm"], ["16 mm²", "49 / 0.64 mm"], ["25 mm²", "98 / 0.58 mm"], ["35 mm²", "133 / 0.58 mm"], ["50 mm²", "133 / 0.68 mm"], ["70 mm²", "189 / 0.68 mm"]];

function SpecsTable({ rows }: { rows: string[][] }) {
  return <div className="spec-table xlpe-spec-table">{rows.map(([label, value]) => <div key={label}><strong>{label}</strong><span>{value}</span></div>)}</div>;
}

function DetailHero({ variant }: { variant: "bv" | "bvr" }) {
  const bv = variant === "bv";
  const title = bv ? "450/750V PVC Insulated Single-Core Building Wire" : "450/750V Flexible PVC Insulated Copper Building Wire";
  const intro = bv ? "Single-core copper building wire with PVC insulation for fixed electrical installations. BV uses a rigid copper conductor, with solid or stranded rigid conductor options depending on conductor size and the confirmed product specification. 60227 IEC 01 is referenced where applicable." : "Single-core PVC insulated building wire with a flexible stranded copper conductor for fixed wiring routes where easier bending and routing are required.";
  const facts = bv ? ["450/750V", "Copper Conductor", "PVC Insulation", "Single Core", "Rigid Conductor", "60227 IEC 01 where applicable"] : ["450/750V", "Copper Conductor", "Flexible Stranded", "PVC Insulation", "Single Core", "BVR"];
  return <section className="product-detail-hero xlpe-product-hero bw-hero"><div className="container product-detail-grid"><div><Link className="back-link" href="/products/building-wires-flexible-cables">Back to Building Wires</Link><span className="eyebrow light">Building Wires / {bv ? "BV" : "BVR"}</span><h1>{title}</h1><p>{intro}</p><div className="xlpe-hero-badges">{facts.map((item) => <span key={item}>{item}</span>)}</div><div className="hero-actions"><Link className="button" href="#inquiry">Request a Quote</Link><Link className="button button-ghost" href="#construction">{bv ? "View Sizes & Construction" : "View Conductor Construction"}</Link></div></div><div className="product-detail-image bw-detail-image"><Image src={`/images/products/building-wires/bw-${variant}-product.png`} alt={bv ? "Huanyu 450/750V PVC insulated rigid copper single-core building wire" : "Huanyu BVR flexible stranded copper conductor PVC insulated building wire"} width={896} height={896} sizes="(max-width: 980px) 100vw, 45vw" priority /></div></div></section>;
}

export function BvBuildingWirePage() {
  const verify: TextItem[] = [["Conductor construction", "Confirm whether the rigid conductor is solid or stranded for the required size."], ["DC resistance", "Review electrical resistance against the confirmed specification."], ["Insulation control", "Confirm insulation dimensions and integrity requirements."], ["Coil length & marking", "Confirm supplied length, cable marking and order labels."]];
  const applications: TextItem[] = [["Residential fixed wiring", "Interior fixed wiring subject to the applicable local electrical code."], ["Commercial interior wiring", "General fixed wiring routes in commercial buildings."], ["Conduit & protected wiring", "Single-core wire installed in a suitable protected wiring system."], ["Lighting & final circuits", "Fixed circuits where permitted by local code and project design."]];
  return <><DetailHero variant="bv" />
    <section className="section" id="construction"><div className="container bw-two-column"><div><span className="eyebrow">Product construction</span><h2>Rigid Conductor Construction for Fixed Wiring</h2><p>BV is often described casually as a “solid wire”, but the rigid-conductor product family can use either solid or stranded rigid conductor construction depending on conductor size and the applicable specification.</p><div className="xlpe-table-wrap bw-compact-table-wrap bw-desktop-conductor-table"><table className="xlpe-table bw-table bw-compact-table"><thead><tr><th>Nominal section</th><th>Representative rigid construction</th></tr></thead><tbody><tr><th scope="row">1.5 mm²</th><td>1 × 1.38 mm solid / 7 × 0.52 mm stranded rigid</td></tr><tr><th scope="row">2.5 mm²</th><td>1 × 1.78 mm solid / 7 × 0.68 mm stranded rigid</td></tr></tbody></table></div><div className="bw-mobile-conductor-cards" aria-label="Representative BV conductor constructions"><article><h3>1.5 mm²</h3><dl><div><dt>Solid</dt><dd>1 × 1.38 mm</dd></div><div><dt>Stranded rigid</dt><dd>7 × 0.52 mm</dd></div></dl></article><article><h3>2.5 mm²</h3><dl><div><dt>Solid</dt><dd>1 × 1.78 mm</dd></div><div><dt>Stranded rigid</dt><dd>7 × 0.68 mm</dd></div></dl></article></div><p className="review-note">Representative construction examples are shown for product identification. Final conductor construction and dimensions are confirmed against the applicable product specification before quotation.</p></div><aside className="bw-standard-card"><h3>Current Huanyu Commercial Size Range</h3><p>Commonly requested</p><ChipRow items={["1.5", "2.5", "4", "6", "10", "16", "25", "35 mm²"]} /><p><strong>Extended current commercial list</strong></p><ChipRow items={["50", "70", "95", "120", "150", "185", "240", "300 mm²"]} /></aside></div></section>
    <section className="section section-muted"><div className="container"><SectionIntro eyebrow="Product specification" title="Specifications at a Glance" /><SpecsTable rows={bvSpecs} /><p className="review-note bw-wide-note">Detailed dimensions, resistance values and test data are confirmed against the applicable current product specification before quotation.</p></div></section>
    <section className="section"><div className="container bw-two-column"><div><span className="eyebrow">Standard review</span><h2>Standard &amp; Specification Review</h2><p>For applicable 60227 IEC 01 (BV) construction, Huanyu references GB/T 5023.3-2008. If the destination market or project specifies another national or international building-wire standard, send the exact designation for technical review before supply is confirmed.</p></div><aside className="review-note">A Chinese BV reference is not presented as automatic compliance with the current IEC, EN, BS or other national designation.</aside></div></section>
    <section className="section section-muted"><div className="container"><SectionIntro eyebrow="Buyer checklist" title="What Buyers Should Verify" /><CardGrid items={verify} className="bw-card-grid bw-four-grid bw-mobile-checklist" /></div></section>
    <QualityBlock /><section className="section bw-flow-section" id="applications"><div className="container"><SectionIntro eyebrow="Applications" title="Typical Applications" /><CardGrid items={applications} className="bw-card-grid bw-four-grid bw-mobile-app-grid" /><p className="review-note bw-wide-note">Final conductor size and installation method must follow the applicable local electrical code and project design.</p></div></section>
    <section className="section section-muted bw-flow-section bw-mobile-packing" id="packing"><div className="container bw-two-column"><div><span className="eyebrow">Supply options</span><h2>Colours &amp; Packing</h2><p>Common electrical colours are confirmed against the order. Typical coil length is 100 m. Other export coil lengths, marking and packing can be reviewed according to confirmed order requirements.</p></div><aside className="bw-standard-card"><h3>Information to confirm</h3><ChipRow items={["Colour", "Coil Length", "Cable Marking", "Packing", "Private-Label Review"]} /></aside></div></section><ComplianceBlock className="bw-flow-section" />
    <section className="section quote-section bw-flow-section" id="inquiry"><div className="container quote-grid"><div><span className="eyebrow light">Quotation review</span><h2>Request a Quote for 450/750V Single-Core Building Wire</h2><p>Size · Conductor Construction · Standard · Colour · Coil Length · Quantity · Destination</p></div><InquiryForm compact /></div></section>
  </>;
}

export function BvrBuildingWirePage() {
  const applications: TextItem[] = [["Distribution boards", "Flexible conductor wiring within the confirmed board design."], ["Electrical panels", "Internal fixed wiring where easier routing assists installation."], ["Routes with more bends", "Interior fixed wiring routes requiring greater installation flexibility."], ["Protected building wiring", "Protected routes where flexible conductor construction assists installation."]];
  return <><DetailHero variant="bvr" />
    <section className="section" id="construction"><div className="container bw-two-column"><div><span className="eyebrow">Product construction</span><h2>Flexible Stranded Conductor for Easier Routing</h2><p>BVR uses multiple copper strands to provide greater installation flexibility than rigid-conductor building wire of the same nominal cross-sectional category. It is intended for fixed wiring applications where easier bending and routing assist installation.</p><p><strong>Reference sizes with current technical data:</strong> 2.5–70 mm²</p><p className="review-note">Additional commercial sizes can be reviewed against the required conductor construction and applicable product specification.</p></div><aside className="bw-standard-card"><h3>Construction identity</h3><ChipRow items={["Single Core", "Flexible Stranded Copper", "PVC Insulation", "No Outer Sheath"]} /></aside></div></section>
    <section className="section section-muted"><div className="container"><SectionIntro eyebrow="Technical reference" title="Reference BVR Conductor Construction" /><div className="xlpe-table-wrap bw-desktop-conductor-table"><table className="xlpe-table bw-table"><thead><tr><th>Nominal section</th><th>Conductor construction</th></tr></thead><tbody>{bvrConstruction.map(([size, construction]) => <tr key={size}><th scope="row">{size}</th><td>{construction}</td></tr>)}</tbody></table></div><div className="bw-mobile-conductor-list" aria-label="Reference BVR conductor constructions">{bvrConstruction.map(([size, construction]) => <div key={size}><strong>{size}</strong><span>{construction}</span></div>)}</div><p className="review-note bw-wide-note">Values are reference construction data from Huanyu&apos;s technical material. Final construction and current-standard values are confirmed before quotation.</p></div></section>
    <section className="section"><div className="container"><SectionIntro eyebrow="Product specification" title="Specifications at a Glance" /><SpecsTable rows={bvrSpecs} /></div></section>
    <section className="section section-muted"><div className="container bw-two-column"><div><span className="eyebrow">Standard review</span><h2>Standard &amp; Specification Review</h2><p>BVR is a Chinese product designation used for flexible PVC insulated building wire. Applicable Chinese construction is reviewed against JB/T 8734.2-2016. If the project specifies an IEC, EN, BS or other national designation, send the exact standard for technical review before supply is confirmed.</p></div><aside className="review-note">BVR is not presented as an automatic equivalent of H07V-K or another overseas product designation.</aside></div></section>
    <section className="section"><div className="container"><SectionIntro eyebrow="Applications" title="Typical Applications" /><CardGrid items={applications} className="bw-card-grid bw-four-grid bw-mobile-app-grid" /><p className="review-note bw-wide-note">Cable selection, conductor size and installation method must follow the applicable local electrical code and project design.</p></div></section>
    <QualityBlock bvr />
    <section className="section bw-mobile-packing"><div className="container bw-two-column"><div><span className="eyebrow">Supply options</span><h2>Colours &amp; Packing</h2><p>Common electrical colours are confirmed against the order. Typical coil length is 100 m. Other export coil lengths, marking and packing can be reviewed according to confirmed order requirements.</p></div><aside className="bw-standard-card"><h3>Information to confirm</h3><ChipRow items={["Colour", "Coil Length", "Cable Marking", "Packing", "Required Documentation"]} /></aside></div></section><ComplianceBlock />
    <section className="section quote-section" id="inquiry"><div className="container quote-grid"><div><span className="eyebrow light">Quotation review</span><h2>Request a Quote for Flexible Building Wire</h2><p>Size · Standard · Colour · Coil Length · Quantity · Destination · Required Documentation</p></div><InquiryForm compact /></div></section>
  </>;
}
